fix: shasum comparation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,18 +28,26 @@ jobs:
         mkdir -p sbom-tmp
         cp -r sbom/* sbom-tmp/
 
+        clean_up() {
+            echo "Removing temporary files..."
+            rm current_hashes.txt new_hashes.txt
+            rm -rf sbom-tmp
+        }
         calculate_hashes() {
-          file=$1
-          echo "Removing timestamp and serialNumber from cyclonedx SBOM..."
-          jq 'del(.metadata.timestamp)' sbom-tmp/cyclonedx.json > sbom-tmp/cyclonedx.json
-          jq 'del(.serialNumber)' sbom-tmp/cyclonedx.json > sbom-tmp/cyclonedx.json
-  
-          echo "Removing timestamp and documentNamespace from spdx SBOM..."
-          jq 'del(.creationInfo.created)' sbom-tmp/spdx.json > sbom-tmp/spdx.json
-          jq 'del(.documentNamespace)' sbom-tmp/spdx.json > sbom-tmp/spdx.json
-  
-          echo "generating hashes..."
-          find ./sbom-tmp -type f -exec sha256sum {} \; > $file
+            file=$1
+            echo "Removing timestamp and serialNumber from cyclonedx SBOM..."
+            jq 'del(.metadata.timestamp)' sbom-tmp/cyclonedx.json > sbom-tmp/cyclonedx.json.tmp && mv sbom-tmp/cyclonedx.json.tmp sbom-tmp/cyclonedx.json
+            jq 'del(.serialNumber)' sbom-tmp/cyclonedx.json > sbom-tmp/cyclonedx.json.tmp && mv sbom-tmp/cyclonedx.json.tmp sbom-tmp/cyclonedx.json
+
+            echo "Removing timestamp and documentNamespace from spdx SBOM..."
+            jq 'del(.creationInfo.created)' sbom-tmp/spdx.json > sbom-tmp/spdx.json.tmp && mv sbom-tmp/spdx.json.tmp sbom-tmp/spdx.json
+            jq 'del(.documentNamespace)' sbom-tmp/spdx.json > sbom-tmp/spdx.json.tmp && mv sbom-tmp/spdx.json.tmp sbom-tmp/spdx.json
+
+            echo "generating hashes and storing them in $file..."
+            
+            sha256sum sbom-tmp/cyclonedx.json >> $file
+            sha256sum sbom-tmp/spdx.json >> $file
+            #cat $file
         }
 
         echo "Calculating current hashes..."
@@ -54,15 +62,14 @@ jobs:
         echo "Comparing hashes..."
         diff current_hashes.txt new_hashes.txt
 
-        echo "Removing temporary files..."
-        rm current_hashes.txt new_hashes.txt
-        rm -rf sbom-tmp
-        
         if [ $? -ne 0 ]; then
-          echo "Error: SBOM hashes do not match, please run 'npm run generate-sbom' locally and commit the changes."
-          exit 1
+            echo "Error: SBOM hashes do not match, please run 'npm run generate-sbom' locally and commit the changes."
+            clean_up    
+            exit 1
         fi
 
         echo "SBOM hashes match!"
+        clean_up
+        exit 0
 
     - run: npm test --if-present
